"""ReleaseNotesAgent — markdown release notes from structured sprint data.

Sibling of :class:`DocumentationAgent` inside ``technical_writers``.
Shares the same Strands ``documentation`` model alias so we don't add a
new model surface for one prompt; the input/output contracts and prompt
are owned here. Issue #371 (Phase 3 of #243).

Failure mode: the agent never raises — if the LLM call or JSON parse
goes sideways it returns a deterministic fallback markdown body with
``llm_failed=True`` so the ReleaseManagerAgent can still write the
release file (releases must remain observable even when the model is
down).
"""

from __future__ import annotations

import json
import logging
from typing import Any

from .models import (
    ReleaseFailure,
    ReleaseNotesInput,
    ReleaseNotesOutput,
    ReleaseStorySummary,
)
from .prompts import SYSTEM_PROMPT, build_user_prompt

logger = logging.getLogger(__name__)

_FALLBACK_SUMMARY = "release notes generated by deterministic fallback (LLM unavailable)"


class ReleaseNotesAgent:
    """Compose markdown release notes for a completed sprint.

    The constructor mirrors :class:`DocumentationAgent`: pass in a
    Strands model directly (tests do this with a stub) or let the
    constructor resolve the shared ``documentation`` model lazily.
    """

    def __init__(self, llm_client: Any | None = None) -> None:
        # Lazy-bound; set on first ``run`` so test suites that monkeypatch
        # ``get_strands_model`` don't pay an import-time cost. Direct
        # injection (an object with an ``Agent``-compatible model
        # interface, or a Strands ``Model`` instance) is also supported.
        self._model = llm_client
        self._model_resolved = llm_client is not None

    def _resolve_model(self) -> Any:
        if self._model_resolved:
            return self._model
        # Imported here so the package is importable without strands
        # in environments where the dependency isn't installed (e.g.
        # CI tests of pure data flows).
        from llm_service import get_strands_model  # noqa: PLC0415

        self._model = get_strands_model("documentation")
        self._model_resolved = True
        return self._model

    def run(self, input_data: ReleaseNotesInput) -> ReleaseNotesOutput:
        """Produce markdown + a one-line summary.

        Always returns a populated ``ReleaseNotesOutput`` — never raises.
        On LLM failure or JSON parse failure, ``llm_failed=True`` is
        set and ``markdown`` is assembled from a deterministic template.
        """
        try:
            from strands import Agent  # noqa: PLC0415 — optional at import time

            payload_json = input_data.model_dump_json()
            prompt = build_user_prompt(payload_json)
            agent = Agent(model=self._resolve_model(), system_prompt=SYSTEM_PROMPT)
            raw = str(agent(prompt)).strip()
            data = json.loads(raw)
            markdown = data.get("markdown") or ""
            summary = data.get("summary") or ""
            if not markdown:
                # The LLM returned something parseable but empty —
                # treat as a degraded response and fall back so we
                # still produce a usable release file.
                logger.warning("ReleaseNotesAgent: LLM returned empty markdown; falling back")
                return self._fallback(input_data, "empty markdown from LLM")
            return ReleaseNotesOutput(markdown=markdown, summary=summary)
        except Exception as exc:
            logger.warning(
                "ReleaseNotesAgent: LLM call failed (%s); using deterministic fallback",
                exc,
            )
            return self._fallback(input_data, str(exc))

    @staticmethod
    def _fallback(input_data: ReleaseNotesInput, error: str) -> ReleaseNotesOutput:
        """Deterministic markdown when the LLM path fails.

        Mirrors the prompt's section order so a downstream tool that
        expects e.g. a "Stories shipped" heading still finds it.
        """
        lines: list[str] = []
        lines.append(f"# Release {input_data.version}")
        lines.append("")
        lines.append(f"_Sprint: {input_data.sprint_name} ({input_data.sprint_id})_")
        if input_data.shipped_at_iso:
            lines.append(f"_Shipped at: {input_data.shipped_at_iso}_")
        lines.append("")
        lines.append("## Highlights")
        lines.append("")
        if input_data.stories:
            for s in input_data.stories[:3]:
                lines.append(f"- {s.title}")
        else:
            lines.append("_No stories recorded for this sprint._")
        lines.append("")
        lines.append("## Stories shipped")
        lines.append("")
        if input_data.stories:
            for s in input_data.stories:
                lines.extend(_render_story(s))
        else:
            lines.append("_None._")
        lines.append("")
        lines.append("## Known issues")
        lines.append("")
        if input_data.failures:
            for f in input_data.failures:
                lines.append(_render_failure(f))
        else:
            lines.append("_No issues recorded — sprint shipped clean._")
        lines.append("")
        lines.append("## Next-sprint candidates")
        lines.append("")
        if input_data.failures:
            # Surface critical/high failures verbatim as candidate seeds.
            top = [f for f in input_data.failures if f.severity in ("critical", "high")]
            if not top:
                top = input_data.failures[:3]
            for f in top[:3]:
                rec = f.recommendation or f.summary
                lines.append(f"- {rec}")
        else:
            lines.append(
                "- Review shipped stories with stakeholders before planning the next sprint."
            )
        lines.append("")
        return ReleaseNotesOutput(
            markdown="\n".join(lines).rstrip() + "\n",
            summary=_FALLBACK_SUMMARY,
            llm_failed=True,
            error=error,
        )


def _render_story(story: ReleaseStorySummary) -> list[str]:
    summary = story.user_story.splitlines()[0].strip() if story.user_story else ""
    bullet = f"- **{story.title}**"
    if summary:
        bullet = f"{bullet} — {summary}"
    out = [bullet]
    for ac in story.acceptance_criteria:
        out.append(f"  - {ac}")
    return out


def _render_failure(failure: ReleaseFailure) -> str:
    where = failure.location or "unspecified location"
    return f"- [{failure.severity}] {failure.summary} ({failure.source}: {where})"
